### ISSUE TITLE
Promoter dataset source

### ISSUE THREAD

**Issue by sebastianIwirth** [jzhoulab/ddsm#8]
Thank you for the interesting paper!

I am having trouble understanding which exact files you used from the FANTOM5 database and how you converted them to the files provided on the ZENODO platform. This was not made clear in the paper, and in the code it is also not stated, as far as I see.
Could you please add some information in the readme about which files you used from the FANTOM5 database and the code you used to preprocess these files?

Thank you in advance!

**Comment by PavelAvdeyev** [comment]
Hello, 

The paper describing Puffin contains all the details about the dataset: https://www.biorxiv.org/content/10.1101/2023.06.27.546584v1 

Best, 
Pavel
